name: Send ChatGPT to Discord

on:
  schedule:
    - cron: '0 12 * * *' # UTC 12:00 = JST 21:00
  workflow_dispatch:

jobs:
  send-gpt:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      PROMPT: "ここにプロンプトを入力"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install openai requests
      - name: Run script
        run: python jouhou.py
